### ISSUE TITLE
STATUS_ACCOUNT_DISABLED - SMB2 Connections, trust domain issues

### ISSUE THREAD

**Issue by colingarvey** [emc-isilon/pike#14]
In authenticating to the cluster via the auth provider which has a primary domain & trust domain - trust domain credentials fail with this error message amongst other kerberos failures. Has anyone seen this?

**Comment by isi-mfurer** [comment]
I'm assuming the same credentials work from a windows client?

Do you get the same error when using NTLM authentication?

**Comment by colingarvey** [comment]
We have two domains; domain1\ and domain2\. Domains have a 2-way trust
relationship at the root level. We've been working day and night with EMC
support, but I'm wondering if dev team has any input.

Domain1\<user> credentials work, Domain2\<user> credentials do not work
from a windows client.

We have not tried NTLM authentication as Kerberos auth is enforced for info
sec purposes. This is incredibly strange because the auth worked perfectly
on OneFS 7.2.1.1 but not on 7.2.1.2.

**Comment by isi-pandrew** [comment]
Colin,

Is this a OneFS issue or a Pike specific issue?  I ask because what you're saying indicates this could be a OneFS authentication issue and not something related to pike.   If so, I advise you to reach out to the appropriate channels about your problem, and they'll be able to diagnose the problem quickly.  Feel free to shoot me an email < patrick.andrew [at ] isilon.com >  and we can follow up there if this is the case.


Thanks!

**Comment by isi-mfurer** [comment]
requesting an update on this issue

**Comment by colingarvey** [comment]
Hello, we got this working. EMC released a patch in 7.2.1.2 that fixed the cross-domain authentication. This is also unrelated to Pike, but at the time I was relatively desperate for a fix since there was widespread production impact.

**Comment by isi-mfurer** [comment]
thank you
